### ISSUE TITLE
[bug] when using this.heat.setOptions change the radius

### ISSUE THREAD

**Issue by yeatszhang** [Esri/esri-leaflet-heatmap-feature-layer#10]
I need to change the radius of heat layer but there is not a api. So i use this.heat object change it directly.
But it doesn't work. Is there any suggestions or support ? 
Thanks for your lib, it helps a lot.

![bug](http://7xksmv.com1.z0.glb.clouddn.com/bug.png)

**Comment by jgravois** [comment]
it is already possible to set your own radius directly in the layer constructor (as shown in [this sample](http://esri.github.io/esri-leaflet/examples/visualize-points-as-a-heatmap.html)), so am i correct to assume you're attempting to modify the value on the fly after the layer has already been instantiated?

if so, i'll need to look into exposing something similar to [`L.heatlayer.setOptions()`](https://github.com/Leaflet/Leaflet.heat#methods).

**Comment by jgravois** [comment]
sorry it took so long, but i finally got around to creating a PR to expose `setOptions()` directly to this plugin.

that said, i couldn't reproduce the problem you initially reported.  the code below was already enough to refresh the display of a heatmap with a new radius.

```js
heatLayer.heat.setOptions({
  radius: 10
});
```

**Comment by yeatszhang** [comment]
Thanks for you support. That's what I need! 😄
