### ISSUE TITLE
Feature suggestion - convert FeatureLayer to HeatmapFeatureLayer

### ISSUE THREAD

**Issue by rowanwins** [Esri/esri-leaflet-heatmap-feature-layer#11]
Gday @jgravois 

I've been wondering if it would be nifty to have a method on FeatureLayer that could convert your layer to a HeatmapFeatureLayer and vice-versa (a method on a HeatmapFeatureLayer to convert to FeatureLayer)?

The use case is having a toggle button on my UI that switches between displaying points and a heatmap... What do you think, would such methods help make that easy? It seems fairly straightforward in my mind to implement but perhaps I'm wrong....

If you think its feasible and useful Im happy to take a look

Cheers
Rowan

**Comment by jgravois** [comment]
my first instinct is that it makes more sense to manage two different layers, and just have the UI add one and remove the other.

that being said, if what you're describing would be more helpful *to you*, i'd be happy to look at a PR and talk about it further.

**Comment by rowanwins** [comment]
Gday @jgravois 

Thanks for the feedback. My UI contains some stuff for setting filters on the data (eg where clauses, date ranges etc), I was trying to avoid the scenario where I have to update both a heatlayer and a featurelayer. 
I'm happy to be guided by your opinion, you're more experienced than I in this stuff and probably have a better idea as to what a scalable solution looks like.

**Comment by jgravois** [comment]
on the contrary, i don't actually spend a lot of time *writing applications*. :smile:

**Comment by rowanwins** [comment]
Ok well perhaps I'll try keeping my objects somewhat in-sync in the first instance, I'll find out how hard that is, and if it proves difficult I'll look at adding this feature. What I basically envisage in the two layer scenario is having
````
function setWhereClauses(){
    heatLayer.setWhere(....)
    featureLayer.setWhere(....)
}
````

The good news is if my scenario is reasonably tricky and I can do it then anyone can :)

**Comment by jgravois** [comment]
closing based on prior feedback, but happy to chat more if it'd be helpful.
