### ISSUE TITLE
refactor to use rollup (and expose class as L.esri.Heat.featureLayer)

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-heatmap-feature-layer#12]
pattern to follow is in Esri/esri-leaflet-clustered-feature-layer#9

**Comment by tyleralves** [comment]
In esri-leaflet-clustered-feature-layer package.json the "main" property is set to 'dist/esri-leaflet-cluster-debug.js'. Is this intentional? Why isn't it set to 'dist/esri-leaflet-cluster.js'?

**Comment by jgravois** [comment]
> Why isn't it set to 'dist/esri-leaflet-cluster.js'?

both [esri-leaflet](https://github.com/Esri/esri-leaflet/blob/master/package.json#L66) and [Leaflet](https://github.com/Leaflet/Leaflet/blob/master/package.json#L25), as well as conventional node packages, typically declare their un-obfuscated build as `main` too. 

from the [npm](https://docs.npmjs.com/files/package.json#main) documentation:

> The main field is a module ID that is the primary entry point to your program. That is, if your package is named foo, and a user installs it, and then does require("foo"), then your main module's exports object will be returned.

i'm fairly confident this is a convention that stems from a common interest in making sure that debugging dependencies is as fruitful as possible.  that being said, front-end developers are definitely welcome to utilize the minified source in production too.

**Comment by jgravois** [comment]
closed via #14 :tada:
